apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-manager-role
  namespace: pvc-cleaner
rules:
- apiGroups:
  - ''
  resources:
  - 'serviceaccounts'
  - 'services'
  verbs:
  - 'create'
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  verbs:
  - 'create'
